CREATE TABLE IF NOT EXISTS recipes (
    id BIGINT PRIMARY KEY,
    family_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    base_servings DECIMAL(10, 2) NOT NULL,
    instructions TEXT,
    note VARCHAR(255) DEFAULT NULL,
    status VARCHAR(16) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_recipe_family_status (family_id, status)
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
    id BIGINT PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    source_id BIGINT DEFAULT NULL,
    name_snapshot VARCHAR(64) NOT NULL,
    category_snapshot VARCHAR(64) NOT NULL,
    quantity DECIMAL(10, 2) NOT NULL,
    unit VARCHAR(16) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_recipe_ingredients_recipe (recipe_id, sort_order)
);

CREATE TABLE IF NOT EXISTS meal_requests (
    id BIGINT PRIMARY KEY,
    family_id BIGINT NOT NULL,
    requester_user_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    note VARCHAR(255) DEFAULT NULL,
    status VARCHAR(16) NOT NULL,
    requested_at DATETIME NOT NULL,
    decided_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_meal_request_family_status (family_id, status),
    KEY idx_meal_request_requester (requester_user_id, requested_at)
);

CREATE TABLE IF NOT EXISTS meal_request_recipes (
    id BIGINT PRIMARY KEY,
    meal_request_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    recipe_name_snapshot VARCHAR(64) NOT NULL,
    base_servings DECIMAL(10, 2) NOT NULL,
    target_servings DECIMAL(10, 2) NOT NULL,
    servings_multiplier DECIMAL(10, 4) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_meal_request_recipe_request (meal_request_id)
);

CREATE TABLE IF NOT EXISTS meal_request_responses (
    id BIGINT PRIMARY KEY,
    meal_request_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    decision VARCHAR(16) NOT NULL,
    comment VARCHAR(255) DEFAULT NULL,
    decided_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_meal_request_user (meal_request_id, user_id),
    KEY idx_meal_response_user_decision (user_id, decision)
);

INSERT INTO ingredient_catalog_system (id, name, category, default_unit, enabled, sort_order)
VALUES
    (11, '鸡腿', '肉类', '克', 1, 11),
    (12, '鸡翅', '肉类', '克', 1, 12),
    (13, '牛肉', '肉类', '克', 1, 13),
    (14, '羊肉', '肉类', '克', 1, 14),
    (15, '排骨', '肉类', '克', 1, 15),
    (16, '五花肉', '肉类', '克', 1, 16),
    (17, '虾', '海鲜', '克', 1, 17),
    (18, '鱼', '海鲜', '条', 1, 18),
    (19, '鱿鱼', '海鲜', '克', 1, 19),
    (20, '豆腐', '豆制品', '盒', 1, 20),
    (21, '豆干', '豆制品', '包', 1, 21),
    (22, '土豆', '蔬菜', '个', 1, 22),
    (23, '洋葱', '蔬菜', '个', 1, 23),
    (24, '青椒', '蔬菜', '个', 1, 24),
    (25, '红椒', '蔬菜', '个', 1, 25),
    (26, '西兰花', '蔬菜', '颗', 1, 26),
    (27, '白菜', '蔬菜', '颗', 1, 27),
    (28, '生菜', '蔬菜', '颗', 1, 28),
    (29, '菠菜', '蔬菜', '把', 1, 29),
    (30, '胡萝卜', '蔬菜', '根', 1, 30),
    (31, '茄子', '蔬菜', '根', 1, 31),
    (32, '玉米', '蔬菜', '根', 1, 32),
    (33, '香菇', '菌菇', '朵', 1, 33),
    (34, '金针菇', '菌菇', '包', 1, 34),
    (35, '杏鲍菇', '菌菇', '根', 1, 35),
    (36, '蒜', '调料', '头', 1, 36),
    (37, '姜', '调料', '块', 1, 37),
    (38, '小葱', '调料', '把', 1, 38),
    (39, '香菜', '调料', '把', 1, 39),
    (40, '鸡精', '调料', '袋', 1, 40),
    (41, '食盐', '调料', '袋', 1, 41),
    (42, '白糖', '调料', '袋', 1, 42),
    (43, '生抽', '调料', '瓶', 1, 43),
    (44, '老抽', '调料', '瓶', 1, 44),
    (45, '蚝油', '调料', '瓶', 1, 45),
    (46, '醋', '调料', '瓶', 1, 46),
    (47, '料酒', '调料', '瓶', 1, 47),
    (48, '食用油', '调料', '瓶', 1, 48),
    (49, '淀粉', '调料', '袋', 1, 49),
    (50, '面粉', '主食', '袋', 1, 50),
    (51, '大米', '主食', '袋', 1, 51),
    (52, '馒头', '主食', '个', 1, 52),
    (53, '饺子', '冷冻', '袋', 1, 53),
    (54, '馄饨', '冷冻', '袋', 1, 54),
    (55, '火腿肠', '加工食品', '根', 1, 55),
    (56, '培根', '加工食品', '包', 1, 56),
    (57, '芝士片', '蛋奶', '包', 1, 57),
    (58, '黄油', '蛋奶', '盒', 1, 58),
    (59, '苹果', '水果', '个', 1, 59),
    (60, '香蕉', '水果', '根', 1, 60),
    (61, '橙子', '水果', '个', 1, 61),
    (62, '柠檬', '水果', '个', 1, 62),
    (63, '草莓', '水果', '盒', 1, 63),
    (64, '酸豆角', '腌制', '袋', 1, 64),
    (65, '榨菜', '腌制', '袋', 1, 65),
    (66, '紫菜', '干货', '包', 1, 66),
    (67, '海带', '干货', '包', 1, 67),
    (68, '木耳', '干货', '包', 1, 68),
    (69, '银耳', '干货', '包', 1, 69),
    (70, '红枣', '干货', '袋', 1, 70),
    (71, '枸杞', '干货', '袋', 1, 71),
    (72, '豆浆', '饮品', '瓶', 1, 72),
    (73, '矿泉水', '饮品', '瓶', 1, 73),
    (74, '橙汁', '饮品', '盒', 1, 74),
    (75, '咖啡', '饮品', '盒', 1, 75),
    (76, '茶叶', '饮品', '盒', 1, 76),
    (77, '辣椒酱', '调料', '瓶', 1, 77),
    (78, '番茄酱', '调料', '瓶', 1, 78),
    (79, '面包', '主食', '袋', 1, 79),
    (80, '方便面', '主食', '袋', 1, 80)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    category = VALUES(category),
    default_unit = VALUES(default_unit),
    enabled = VALUES(enabled),
    sort_order = VALUES(sort_order);
